AWSTemplateFormatVersion: '2010-09-09'
Description: WMAI Simple Website Deployment

Parameters:
  GitRepoURL:
    Type: String
    Description: GitHub repository URL
    Default: https://github.com/yogeshjha06/Survey.git
  GitBranch:
    Type: String
    Description: Git branch to deploy
    Default: main

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c94855ba95c71c99  # Amazon Linux 2
    us-west-2:
      AMI: ami-0d70546e43a941d70  # Amazon Linux 2

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      SecurityGroupIds: [!Ref WebServerSecurityGroup]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > >(tee /var/log/user-data.log) 2>&1
          
          # Install web server and PHP
          yum update -y
          amazon-linux-extras install php8.0 -y
          yum install -y httpd git
          
          # Configure Apache
          systemctl start httpd
          systemctl enable httpd
          usermod -a -G apache ec2-user
          chown -R ec2-user:apache /var/www
          chmod 2775 /var/www
          
          # Deploy website
          rm -rf /var/www/html/*
          git clone -b ${GitBranch} ${GitRepoURL} /var/www/html/
          
          # Ensure proper permissions
          chmod -R 775 /var/www/html
          find /var/www/html -type d -exec chmod 2775 {} \;
          find /var/www/html -type f -exec chmod 0664 {} \;
          
          # Restart Apache
          systemctl restart httpd

      Tags:
        - Key: Name
          Value: wmai-website
        - Key: Project
          Value: WMAI

Outputs:
  WebsiteURL:
    Description: URL to access the website
    Value: !Sub "http://${WebServerInstance.PublicDnsName}/"
